# This file is kept for compatibility but Jekyll processing is disabled by .nojekyll

# Disable Jekyll entirely
safe: true
include: []

# Base settings
baseurl: ""
url: ""

# Site settings
title: "Игровой Портал"
description: "Коллекция увлекательных игр"

# Disable all Jekyll processing
markdown: kramdown
plugins: []

# Exclude everything to prevent processing
exclude:
  - ./*
  - ./*/**
  - .github/
  - .git/
  - .gitignore
  - .nojekyll
  - README.md
  - _config.yml
  - vercel.json
  - now.json
  - package.json
  - package-lock.json
  - node_modules/

# Disable all collections and processing
collections: {}
defaults: []

# Disable all Jekyll features
future: false
show_drafts: false
limit_posts: 0
keep_files: []

# Disable directory output
permalink: none

# Disable feed generation
feed:
  enabled: false

# Оптимизации
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  ignore:
    envs: [development]
