# Minimal Jekyll configuration
# This file is kept for compatibility but Jekyll processing is disabled by .nojekyll

# Base settings
baseurl: "" # Empty for root, or "/your-repo-name" if using GitHub Pages
url: "" # Your site's base URL (e.g., "https://yourusername.github.io")

# Site settings
title: "Игровой Портал"
description: "Коллекция увлекательных игр"

# Build settings
markdown: kramdown
plugins: []

# Include all files (no Jekyll processing)
include: ["*"]

# Exclude these files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md
  - package.json
  - package-lock.json
  - .gitignore
  - .nojekyll

# Disable Jekyll's default processing
future: false
show_drafts: false
limit_posts: 0
keep_files: ["assets", "mines"]

# Disable directory output for static site
permalink: none

# Disable default collections
collections: {}

defaults: []

# Disable feed generation
feed:
  enabled: false

# Настройки для GitHub Pages
remote_theme: pages-themes/cayman@v0.2.0

# Оптимизации
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  ignore:
    envs: [development]
